#!/usr/bin/env python3

import os
text = '''<!--- DO NOT EDIT THIS FILE. Generated by [[GEN]]-->
# Inferring conductivity from temperature

'''


def add_dir(subdir, title, cmd, img=True):
    global text
    text += f"### {title}\n\n"
    text += "```\n"
    text += f"{cmd}\n"
    text += "```\n"
    text += f"Output directory `{subdir}`:\n\n"
    text += f"* [`train.log`]([[EXAMPLES]]/[[OUTDIR]]/{subdir}/train.log)\n"
    if img:
        text += f"* [`u_00010.png`]([[EXAMPLES]]/[[OUTDIR]]/{subdir}/u_00010.png)  \n"
        text += f'  <img src="[[EXAMPLES]]/[[OUTDIR]]/{subdir}/u_00010.png" height=200>\n'
        text += f"* [`k_00010.png`]([[EXAMPLES]]/[[OUTDIR]]/{subdir}/k_00010.png)  \n"
        text += f'  <img src="[[EXAMPLES]]/[[OUTDIR]]/{subdir}/k_00010.png" height=150>\n'
    text += "\n\n"


add_dir("out_ref", "Reference solution", "case=0 outdir=out_ref ./run", img=0)
add_dir("out_odiln", "ODIL Newton", "case=2n outdir=out_odiln ./run")
add_dir("out_odil", "ODIL Adam", "case=2 outdir=out_odil ./run")
add_dir("out_pinn", "PINN Adam", "case=2p gpus=0 outdir=out_pinn ./run")

outdir = "heat"
gen = text
gen = gen.replace('[[GEN]]', os.path.basename(__file__))
gen = gen.replace('[[EXAMPLES]]', "https://cselab.github.io/odil/examples")
gen = gen.replace('[[OUTDIR]]', outdir)
with open("README.md", 'w') as f:
    f.write(gen)
