import sphinx_gallery
import sphinx_gallery.gen_rst

extensions = [
    "sphinx_gallery.gen_gallery",
]
sphinx_gallery_conf = {
    'examples_dirs': '../examples',
    'gallery_dirs': 'auto_examples',
    'show_signature': False,
}
html_theme = 'theme'
html_theme_path = ['.']
pygments_style = 'sphinx'

sphinx_gallery.gen_rst.EXAMPLE_HEADER = """
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "{0}"
.. LINE NUMBERS ARE GIVEN BELOW.

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_{1}:

"""

sphinx_gallery.gen_rst.CODE_DOWNLOAD = """
.. _sphx_glr_download_{3}:

.. only:: html

  .. container:: sphx-glr-footer sphx-glr-footer-example

{2}

{4}
    .. container:: sphx-glr-download sphx-glr-download-python

      :download:`Download Python source code: {0} <{0}>`

    .. container:: sphx-glr-download sphx-glr-download-jupyter

      :download:`Download Jupyter notebook: {1} <{1}>`

    .. container:: sphx-glr-download sphx-glr-download-colab

      :download:`Open in google colab: {1} <{1}>`

"""
